<?php

namespace center\modules\message\models;

use center\models\Pagination;
use Yii;

/**
 * This is the model class for table "news".
 *
 * @property string $id
 * @property string $title
 * @property string $pic
 * @property integer $type
 * @property string $content
 * @property string $desc
 * @property string $mid
 * @property string $ctime
 * @property string $utime
 */
class News extends \yii\db\ActiveRecord
{
    public function beforeSave($insert)
    {
        $this->mid = Yii::$app->user->identity->getId();
        if ($insert) {
            $this->ctime = $this->utime = time();
        } else {
            $this->utime = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'mid', 'ctime', 'utime'], 'integer'],
            [['type', 'content', 'desc', 'title'], 'required'],
            [['content'], 'string'],
            [['title'], 'string', 'max' => 60],
            [['pic'], 'string', 'max' => 255],
            [['pic'], 'file', 'extensions' => 'jpg, png', 'mimeTypes' => 'image/jpeg, image/png',],
        ];
    }
    /**
     * 要搜索的字段
     * @return array
     */
    public function getSearchInput()
    {
        //扩展字段加入搜索
        $exField = [];

        return yii\helpers\ArrayHelper::merge([
            'title' => [
                'label' => Yii::t('app', '文章标题')
            ],
            'type' => [
                'label' => Yii::t('app', '文章类型'),
                'list' => [
                    '' => '请选择',
                    1 => '校内新闻',
                    2 => '大赛新闻',
                    3 => '行业新闻'
                ]
            ],
            'ctime' => [
                'label' => Yii::t('app', '发布时间')
            ],

        ], $exField);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => '文章标题',
            'pic' => '文章图片',
            'type' => '文章类型',
            'desc' => '文章描述',
            'content' => '文章内容',
            'mid' => 'Mid',
            'ctime' => 'Ctime',
            'utime' => 'Utime',
        ];
    }

    public function getAttributesList()
    {
        //1校内新闻2大赛新闻3行业新闻
        return [
            'types' => [
                '' => '请选择',
                1 => '校内新闻',
                2 => '大赛新闻',
                3 => '行业新闻'
            ]
        ];
    }

    /**
     * @param $param
     * @return array
     */
    public function getList($param)
    {
        try {
            $query = self::find();
            $pagesSize = 10;

            foreach ($param as $k => $v) {
                if (!empty($v) && $this->hasAttribute($k)) {
                    if ($k == 'title') {
                        $query->andWhere("$k like :title", [':title' => "%".$v."%"]);
                    } else if ($k == 'ctime') {
                        $query->andWhere('ctime >= :start', [':start' => strtotime($v)]);
                    }else {
                        $query->andWhere("$k = :$k", [":$k" => $v]);
                    }
                }
            }
            $pages = new Pagination([
                'totalCount' => $query->count(),
                'pageSize' => $pagesSize
            ]);
            $list = $query->offset($pages->offset)
                ->limit($pages->limit)
                ->asArray()
                ->all();
            $rs = ['code' => 1, 'data' => $list, 'pagination' => $pages];
        } catch (\Exception $e) {
            $rs = ['code' => 500, 'msg' => '获取异常'];
        }

        return $rs;
    }
}
