<?php

namespace center\modules\report\models;

use Yii;

/**
 * This is the model class for table "online_product_user_month".
 *
 * @property integer $id
 * @property integer $product_id
 * @property string $product_name
 * @property integer $date
 * @property integer $normal_amount
 * @property integer $abnormal_amount
 */
class OnlineProductUserMonth extends \yii\db\ActiveRecord
{

    public $start_At; //开始时间
    public $stop_At; //截止时间
    public $showField; //相关的产品信息

    public function getShowField(){
        return $this->showField;
    }

    public function setShowField($showField){
        $this->showField = $showField;
    }

    public function getStopAt(){
        return $this->stop_At;
    }

    public function setStopAt($stop_At){
        $this->stop_At = $stop_At;
    }

    public function getStartAt(){
        return $this->start_At;
    }

    public function setStartAt($start_At){
        $this->start_At = $start_At;
    }

    /**
     * 设置场景
     *
     * */
    public function scenarios()
    {
        $scenarios =  parent::scenarios(); // TODO: Change the autogenerated stub
        $scenarios['user-month'] = ['start_At','stop_At','showField'];
        return $scenarios;
    }
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'online_product_user_month';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['product_id', 'product_name', 'date', 'normal_amount', 'abnormal_amount'], 'required'],
            [['product_id', 'date', 'normal_amount', 'abnormal_amount'], 'integer'],
            [['product_name'], 'string', 'max' => 64],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'product_id' => 'Product ID',
            'product_name' => 'Product Name',
            'date' => 'Date',
            'normal_amount' => 'Normal Amount',
            'abnormal_amount' => 'Abnormal Amount',
        ];
    }
    
    /**
     * 获取指定时间段内的产品人数
     * 
     * 
     * */
    public function getUserAmountMonth($excel){
        $startTime = strtotime($this->start_At);
        $stopTime = strtotime($this->stop_At);
        $query = new \yii\db\Query();
        $query->select(['product_name','product_id','normal_amount','abnormal_amount','date']);
        $query->from(self::tableName());
        $query->where(['>=','date',$startTime]);
        $query->andWhere(['<=','date',$stopTime]);
        $query->andFilterWhere(['in','product_id',$this->showField]);
        $query->groupBy(['product_id']);
        $query->indexBy('product_id');
        $query->orderBy('date');
        $data = $query->all();
        if($data){
            $result = [];
            foreach ($data as $key => $value){
                $temp['product_id'] = $value['product_id'];
                $temp['product_name'] = $value['product_name'];
                $temp['normal_amount'] = $value['normal_amount'];
                $temp['abnormal_amount'] = $value['abnormal_amount'];
                $temp['date'] = date('Y-m',$value['date']);
                $result['table'][] = $temp;
                unset($temp);
            }
            if(!$excel){
                return $result;
            }else{
                $header = [
                    Yii::t('app','product_id'),
                    Yii::t('app','product_name'),
                    Yii::t('app','normal_amount'),
                    Yii::t('app','abnormal_amount'),
                    Yii::t('app','date'),
                ];
                $data = [];
                foreach ($result['table'] as $key => $value){
                    $data[] = array_values($value);
                }
                array_unshift($data,$header);
                $title = 'statistics result';
                $file = $title.'.xls';
                $res['data'] = $data;
                $res['title'] = $title;
                $res['file'] = $file;
                return $res;
            }
        }else{
            return [];
        }
    }
}
